modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nathanrreed/Nuclearcraft-Neohaul/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

enumExtensions="META-INF/enumextensions.json"

updateJSONURL="https://api.modrinth.com/updates/azurum-miner/forge_updates.json?neoforge=only"
displayURL="https://github.com/nathanrreed/Nuclearcraft-Neohaul"
logoFile="logo.png"

credits="tomdodd4598"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="terrablender"
    type="required"
    versionRange="${terrablender_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="zerocore"
    type="required"
    versionRange="${zerocore_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="computercraft"
    type="optional"
    versionRange="${cct_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="emi"
    type="optional"
    versionRange="${emi_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="${jei_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="optional"
    versionRange="${patchouli_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fusion"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"