package com.nred.nuclearcraft.datagen.recipes.processor;

import com.nred.nuclearcraft.recipe.ProcessorRecipeBuilder;
import com.nred.nuclearcraft.recipe.processor.CentrifugeRecipe;
import net.minecraft.data.recipes.RecipeOutput;

import java.util.List;

import static com.nred.nuclearcraft.helpers.FissionConstants.FISSION_FUEL_FLUIDS;
import static com.nred.nuclearcraft.helpers.RecipeHelpers.probabilityPacker;
import static com.nred.nuclearcraft.registration.FluidRegistration.*;

public class CentrifugeProvider {
    public CentrifugeProvider(RecipeOutput recipeOutput) {
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 4 / 3.0, 1).addFluidInput(MOLTEN_MAP.get("boron"), 192).addFluidResult(MOLTEN_MAP.get("boron_11"), 144).addFluidResult(MOLTEN_MAP.get("boron_10"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 10 / 9.0, 1).addFluidInput(MOLTEN_MAP.get("lithium"), 160).addFluidResult(MOLTEN_MAP.get("lithium_7"), 144).addFluidResult(MOLTEN_MAP.get("lithium_6"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 0.5).addFluidInput(FLAMMABLE_MAP.get("redstone_ethanol"), 500).addFluidResult(FLAMMABLE_MAP.get("ethanol"), 500).addFluidResult(MOLTEN_MAP.get("redstone"), 400).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 10 / 9.0, 1).addFluidInput(MOLTEN_MAP.get("uranium"), 160).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), 16).save(recipeOutput);

        for (String name : List.of("iron", "gold", "prismarine", "copper", "tin", "lead", "boron", "lithium", "magnesium", "manganese", "aluminum", "silver", "enderium")) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get(name + "_nak"), 144).addFluidResult(MOLTEN_MAP.get(name), 144).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        }
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("redstone_nak"), 144).addFluidResult(MOLTEN_MAP.get("redstone"), 200).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("quartz_nak"), 144).addFluidResult(MOLTEN_MAP.get("quartz"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("obsidian_nak"), 144).addFluidResult(MOLTEN_MAP.get("obsidian"), 360).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("nether_brick_nak"), 144).addFluidResult(MOLTEN_MAP.get("nether_brick"), 360).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("glowstone_nak"), 144).addFluidResult(MOLTEN_MAP.get("glowstone"), 500).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("lapis_nak"), 144).addFluidResult(MOLTEN_MAP.get("lapis"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("slime_nak"), 144).addFluidResult(MOLTEN_MAP.get("slime"), 288).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("end_stone_nak"), 144).addFluidResult(MOLTEN_MAP.get("end_stone"), 360).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("purpur_nak"), 144).addFluidResult(MOLTEN_MAP.get("purpur"), 360).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("diamond_nak"), 144).addFluidResult(MOLTEN_MAP.get("diamond"), 666).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("emerald_nak"), 144).addFluidResult(MOLTEN_MAP.get("emerald"), 666).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("fluorite_nak"), 144).addFluidResult(MOLTEN_MAP.get("fluorite"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("villiaumite_nak"), 144).addFluidResult(MOLTEN_MAP.get("villiaumite"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("carobbiite_nak"), 144).addFluidResult(MOLTEN_MAP.get("carobbiite"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("arsenic_nak"), 144).addFluidResult(HOT_GAS_MAP.get("arsenic"), 1332).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("liquid_nitrogen_nak"), 144).addFluidResult(CUSTOM_FLUID_MAP.get("liquid_nitrogen"), 250).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("liquid_helium_nak"), 144).addFluidResult(CUSTOM_FLUID_MAP.get("liquid_helium"), 250).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("cryotheum_nak"), 144).addFluidResult(CUSTOM_FLUID_MAP.get("cryotheum"), 250).addFluidResult(COOLANT_MAP.get("nak"), 144).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("leu_233"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 128).addFluidResult(FISSION_FUEL_MAP.get("uranium_233"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("heu_233"), 64).addFluidResult(FISSION_FUEL_MAP.get("leu_233"), 96).addFluidResult(FISSION_FUEL_MAP.get("uranium_233"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("leu_235"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 128).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("heu_235"), 64).addFluidResult(FISSION_FUEL_MAP.get("leu_235"), 96).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("len_236"), 144).addFluidResult(FISSION_FUEL_MAP.get("neptunium_237"), 128).addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hen_236"), 64).addFluidResult(FISSION_FUEL_MAP.get("len_236"), 96).addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), 48).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lep_239"), 144).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 128).addFluidResult(FISSION_FUEL_MAP.get("plutonium_239"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hep_239"), 64).addFluidResult(FISSION_FUEL_MAP.get("lep_239"), 96).addFluidResult(FISSION_FUEL_MAP.get("plutonium_239"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lep_241"), 144).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 128).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hep_241"), 64).addFluidResult(FISSION_FUEL_MAP.get("lep_241"), 96).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 48).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("mix_239"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 128).addFluidResult(FISSION_FUEL_MAP.get("plutonium_239"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("mix_241"), 64).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 128).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lea_242"), 144).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 128).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hea_242"), 64).addFluidResult(FISSION_FUEL_MAP.get("lea_242"), 96).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), 48).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lecm_243"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 128).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hecm_243"), 64).addFluidResult(FISSION_FUEL_MAP.get("lecm_243"), 96).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lecm_245"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 128).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hecm_245"), 64).addFluidResult(FISSION_FUEL_MAP.get("lecm_245"), 96).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lecm_247"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 128).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hecm_247"), 64).addFluidResult(FISSION_FUEL_MAP.get("lecm_247"), 96).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), 48).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("leb_248"), 144).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 128).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("heb_248"), 64).addFluidResult(FISSION_FUEL_MAP.get("leb_248"), 96).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 48).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lecf_249"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 128).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hecf_249"), 64).addFluidResult(FISSION_FUEL_MAP.get("lecf_249"), 96).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 48).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("lecf_251"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 128).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), 16).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("hecf_251"), 64).addFluidResult(FISSION_FUEL_MAP.get("lecf_251"), 96).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), 48).save(recipeOutput);

        for (String name : FISSION_FUEL_FLUIDS) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get(name + "_fluoride_flibe"), 72).addFluidResult(FISSION_FUEL_MAP.get(name + "_fluoride"), 72).addFluidResult(MOLTEN_MAP.get("flibe"), 72).save(recipeOutput);
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_" + name + "_fluoride_flibe"), 72).addFluidResult(FISSION_FUEL_MAP.get("depleted_" + name + "_fluoride"), 72).addFluidResult(MOLTEN_MAP.get("flibe"), 72).save(recipeOutput);
        }

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_tbu"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_233"), 16).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 80).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), 16).addFluidResult(FISSION_FUEL_MAP.get("neptunium_237"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leu_233"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 80).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 16).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heu_233"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), 16).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 32).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 48).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(76, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leu_235"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 64).addFluidResult(FISSION_FUEL_MAP.get("plutonium_239"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 32).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heu_235"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 48).addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 32).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(76, 16)).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_len_236"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 64).addFluidResult(FISSION_FUEL_MAP.get("neptunium_237"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 32).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hen_236"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 64).addFluidResult(FISSION_FUEL_MAP.get("plutonium_238"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 16).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), probabilityPacker(75, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lep_239"), 144).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 80).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hep_239"), 144).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 64).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(75, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lep_241"), 144).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 80).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 16).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hep_241"), 144).addFluidResult(FISSION_FUEL_MAP.get("americium_241"), 16).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 48).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 32).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(75, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_mix_239"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 64).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 32).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_mix_241"), 144).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), 48).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), 16).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), 48).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lea_242"), 144).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 48).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 48).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hea_242"), 144).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), 48).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 32).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(75, 16)).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_243"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 64).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(25, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 32).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(25, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_243"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), 16).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 48).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(75, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 32).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(75, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_245"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 64).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(30, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(20, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_245"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 48).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(90, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(60, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_247"), 144).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), 80).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(30, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(20, 16)).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_247"), 144).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 64).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), probabilityPacker(90, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), 16).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(60, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leb_248"), 144).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), 80).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(30, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), 16).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(20, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heb_248"), 144).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), 16).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), 16).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(90, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_251"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 48).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(60, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecf_249"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(30, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(20, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecf_249"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_250"), 16).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(90, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), probabilityPacker(60, 16)).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecf_251"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(30, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(90, 16)).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecf_251"), 144).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), probabilityPacker(20, 16))
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), 32).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), probabilityPacker(60, 16)).save(recipeOutput);
    }
}