package com.nred.nuclearcraft.datagen.recipes.processor;

import com.nred.nuclearcraft.recipe.ProcessorRecipeBuilder;
import com.nred.nuclearcraft.recipe.processor.CentrifugeRecipe;
import net.minecraft.data.recipes.RecipeOutput;

import java.util.List;

import static com.nred.nuclearcraft.helpers.FissionConstants.FISSION_FUEL_FLUIDS;
import static com.nred.nuclearcraft.registration.FluidRegistration.*;
import static com.nred.nuclearcraft.util.FluidStackHelper.*;

public class CentrifugeProvider {
    public CentrifugeProvider(RecipeOutput recipeOutput) {
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 4 / 3.0, 1).addFluidInput(MOLTEN_MAP.get("boron"), NUGGET_VOLUME * 12).addFluidResult(MOLTEN_MAP.get("boron_11"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("boron_10"), NUGGET_VOLUME * 3).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 10 / 9.0, 1).addFluidInput(MOLTEN_MAP.get("lithium"), NUGGET_VOLUME * 10).addFluidResult(MOLTEN_MAP.get("lithium_7"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("lithium_6"), NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 0.5).addFluidInput(FLAMMABLE_MAP.get("redstone_ethanol"), BUCKET_VOLUME / 2).addFluidResult(FLAMMABLE_MAP.get("ethanol"), BUCKET_VOLUME / 2).addFluidResult(MOLTEN_MAP.get("redstone"), REDSTONE_DUST_VOLUME * 4).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 0.5).addFluidInput(MOLTEN_MAP.get("bacro_nio"), INGOT_VOLUME / 2).addFluidResult(MOLTEN_MAP.get("nickel_oxide"), INGOT_VOLUME / 2).addFluidResult(MOLTEN_MAP.get("bacro"), INGOT_VOLUME / 2).save(recipeOutput);

        for (String name : List.of("iron", "gold", "prismarine", "copper", "tin", "lead", "boron", "lithium", "magnesium", "manganese", "aluminum", "silver", "enderium")) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get(name + "_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get(name), INGOT_VOLUME).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        }
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("redstone_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("redstone"), REDSTONE_DUST_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("quartz_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("quartz"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("obsidian_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("obsidian"), SEARED_MATERIAL_VOLUME * 5).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("nether_brick_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("nether_brick"), SEARED_MATERIAL_VOLUME * 5).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("glowstone_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("glowstone"), BUCKET_VOLUME / 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("lapis_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("lapis"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("slime_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("slime"), INGOT_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("end_stone_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("end_stone"), SEARED_MATERIAL_VOLUME * 5).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("purpur_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("purpur"), SEARED_MATERIAL_VOLUME * 5).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("diamond_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("diamond"), GEM_VOLUME).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("emerald_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("emerald"), GEM_VOLUME).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("fluorite_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("fluorite"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("villiaumite_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("villiaumite"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("carobbiite_nak"), INGOT_VOLUME).addFluidResult(MOLTEN_MAP.get("carobbiite"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("arsenic_nak"), INGOT_VOLUME).addFluidResult(HOT_GAS_MAP.get("arsenic"), GEM_VOLUME * 2).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("liquid_nitrogen_nak"), INGOT_VOLUME).addFluidResult(CUSTOM_FLUID_MAP.get("liquid_nitrogen"), BUCKET_VOLUME / 4).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("liquid_helium_nak"), INGOT_VOLUME).addFluidResult(CUSTOM_FLUID_MAP.get("liquid_helium"), BUCKET_VOLUME / 4).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(COOLANT_MAP.get("cryotheum_nak"), INGOT_VOLUME).addFluidResult(CUSTOM_FLUID_MAP.get("cryotheum"), BUCKET_VOLUME / 4).addFluidResult(COOLANT_MAP.get("nak"), INGOT_VOLUME).save(recipeOutput);

        // Fission Materials

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 10 / 9.0, 1).addFluidInput(MOLTEN_MAP.get("uranium"), NUGGET_VOLUME * 10).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), NUGGET_VOLUME).save(recipeOutput);

        addFissionFuelIsotopeRecipes(recipeOutput, "u", "uranium", 238, 233, 235);
        addFissionFuelIsotopeRecipes(recipeOutput, "n", "neptunium", 237, 236);
        addFissionFuelIsotopeRecipes(recipeOutput, "p", "plutonium", 242, 239, 241);
        for (int fissile : new int[]{239, 241}) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("mix_" + fissile), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 8).addFluidResult(FISSION_FUEL_MAP.get("plutonium_" + fissile), NUGGET_VOLUME).save(recipeOutput);
        }
        addFissionFuelIsotopeRecipes(recipeOutput, "a", "americium", 243, 242);
        addFissionFuelIsotopeRecipes(recipeOutput, "cm", "curium", 246, 243, 245, 247);
        addFissionFuelIsotopeRecipes(recipeOutput, "b", "berkelium", 247, 248);
        addFissionFuelIsotopeRecipes(recipeOutput, "cf", "californium", 252, 249, 251);

        for (String name : FISSION_FUEL_FLUIDS) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get(name + "_fluoride_flibe"), INGOT_VOLUME / 2).addFluidResult(FISSION_FUEL_MAP.get(name + "_fluoride"), INGOT_VOLUME / 2).addFluidResult(MOLTEN_MAP.get("flibe"), INGOT_VOLUME / 2).save(recipeOutput);
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 0.5, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_" + name + "_fluoride_flibe"), INGOT_VOLUME / 2).addFluidResult(FISSION_FUEL_MAP.get("depleted_" + name + "_fluoride"), INGOT_VOLUME / 2).addFluidResult(MOLTEN_MAP.get("flibe"), INGOT_VOLUME / 2).save(recipeOutput);
        }

        // Fuel Reprocessing

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_tbu"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_233"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("neptunium_237"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leu_233"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heu_233"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_235"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 75, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 76, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leu_235"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("plutonium_239"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 25, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heu_235"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("neptunium_236"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 75, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 76, NUGGET_VOLUME).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_len_236"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("neptunium_237"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 25, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hen_236"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("plutonium_238"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 75, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("caesium_137"), 75, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lep_239"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hep_239"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 75, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 75, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lep_241"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hep_241"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_242"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 75, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 75, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_mix_239"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_mix_241"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("uranium_238"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("plutonium_241"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("strontium_90"), 25, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("plutonium_242"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lea_242"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 25, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hea_242"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("americium_243"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("curium_243"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 75, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 75, NUGGET_VOLUME).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_243"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 25, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 25, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_243"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_245"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 75, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 75, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_245"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 30, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 20, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_245"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FUEL_MAP.get("curium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 90, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 60, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecm_247"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("curium_246"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 30, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 20, NUGGET_VOLUME).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecm_247"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 4).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("molybdenum"), 90, 2 * NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 60, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_leb_248"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("berkelium_247"), NUGGET_VOLUME * 5).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 30, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_251"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 20, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_heb_248"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("berkelium_248"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_249"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 90, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_251"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 3).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 60, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecf_249"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 30, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 20, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecf_249"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_250"), NUGGET_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 90, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("promethium_147"), 60, NUGGET_VOLUME).save(recipeOutput);

        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_lecf_251"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 30, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 90, NUGGET_VOLUME).save(recipeOutput);
        new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("depleted_hecf_251"), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FLUID_MAP.get("ruthenium_106"), 20, NUGGET_VOLUME)
                .addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME * 2).addFluidResult(FISSION_FUEL_MAP.get("californium_252"), NUGGET_VOLUME).addFluidResult(FISSION_FLUID_MAP.get("europium_155"), 60, NUGGET_VOLUME).save(recipeOutput);
    }

    public void addFissionFuelIsotopeRecipes(RecipeOutput recipeOutput, String suffix, String element, int fertile, int... fissiles) {
        for (int fissile : fissiles) {
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("le" + suffix + "_" + fissile), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get(element + "_" + fertile), NUGGET_VOLUME * 8).addFluidResult(FISSION_FUEL_MAP.get(element + "_" + fissile), NUGGET_VOLUME).save(recipeOutput);
            new ProcessorRecipeBuilder(CentrifugeRecipe.class, 1, 1).addFluidInput(FISSION_FUEL_MAP.get("he" + suffix + "_" + fissile), INGOT_VOLUME).addFluidResult(FISSION_FUEL_MAP.get(element + "_" + fertile), NUGGET_VOLUME * 6).addFluidResult(FISSION_FUEL_MAP.get(element + "_" + fissile), NUGGET_VOLUME * 3).save(recipeOutput);
        }
    }
}