name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: madhead/read-java-properties@latest
        id: gradle_props
        with:
          file: gradle.properties
          all: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.gradle_props.outputs.java_version }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          body_path: Changelog.md
          tag_name: v${{ steps.gradle_props.outputs.minecraft_version }}-${{ steps.gradle_props.outputs.mod_version }}
          target_commitish: ${{ github.sha }}

      - name: Publish
        run: sh gradlew modrinth publish # curseforge TODO currently not working
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}